language: python
os:
    - linux

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install -r requirements.txt
script: python installDependencies.py && python runAllTests.py test
branches:
    only: 
    - master
    - development

