Configuration:
    type: object
    description: The configuration
    additionalProperties : false
    properties:
      workflows_path:
        type: string
        description: The path to the workflows
      templates_path:
        type: string
        description: The path to the workflow templates
      db_path:
        type: string
        description: The path to the primary WALKOFF database
      case_db_path:
        type: string
        description: The path to the case database
      log_config_path:
        type: string
        description: The path to the logging configuration
      host:
        type: string
        description: The server's host URL
      port:
        type: integer
        description: The server's port
        minimum: 0
        maximum: 65535
      walkoff_db_type:
        type: string
        description: The type of database used by the primary WALKOFF database
        enum: [sqlite, mysql, postgresql, oracle, mssql]
      case_db_type:
        type: string
        description: The type of database used by the case database
        enum: [sqlite, mysql, postgresql, oracle, mssql]
      https:
        type: boolean
        description: Toggle HTTPS on/off
      tls_version:
        type: string
        description: The version of TLS to use
        enum: ['1.1', '1.2', '1.3']
      clear_case_db_on_startup:
        type: boolean
        description: Should the case database be cleared upon a server restart?

